select P.CODIGO, P.NOME, P.CODUSUARIO, P.DEFICIENTEAUDITIVO, P.DEFICIENTEFALA, P.DEFICIENTEVISUAL, P.DEFICIENTEMENTAL from ppessoa P
WHERE (select count(A.RA) from saluno A where A.CODPESSOA = P.CODIGO) > 1
Order by P.NOME